[package]
authors.workspace = true
edition.workspace = true
name = "vsml_audio_mixer"
version.workspace = true

[dependencies]
vsml_common_audio.workspace = true
vsml_core.workspace = true

dasp.workspace = true
