[package]
authors.workspace = true
edition.workspace = true
name = "vsml_core"
version.workspace = true

[dependencies]
phf.workspace = true
regex.workspace = true
thiserror.workspace = true

[dev-dependencies]
mockall.workspace = true
