[package]
authors.workspace = true
edition.workspace = true
name = "vsml_parser"
version.workspace = true

[dependencies]
vsml_ast.workspace = true

nom.workspace = true
regex.workspace = true
roxmltree.workspace = true
thiserror.workspace = true

[dev-dependencies]
mockall.workspace = true
