[package]
authors.workspace = true
edition.workspace = true
name = "vsml_iv_converter"
version.workspace = true

[dependencies]
vsml_ast.workspace = true
vsml_core.workspace = true

[dev-dependencies]
mockall.workspace = true
